export const CMD = {
  getItems: 'get_items',
  createItem: 'create_item',
  updateItem: 'update_item',
  deleteItem: 'delete_item',
  getConfig: 'get_config',
  setConfig: 'set_config',
  getLastSeenFeature: 'get_last_seen_feature',
  setLastSeenFeature: 'set_last_seen_feature',
  setBadgeCount: 'set_badge_count',
  httpRequest: 'http_request',
  notify: 'notify',
  openUrl: 'open_url',
  runInTerminal: 'run_in_terminal',
  openStageLogin: 'open_stage_login',
  confirmStageLogin: 'confirm_stage_login',
  fetchGridData: 'fetch_grid_data',
  cancelGridFetch: 'cancel_grid_fetch',
  dockerListServices: 'docker_list_services',
  dockerServiceStatus: 'docker_service_status',
  dockerServiceAction: 'docker_service_action',
  dockerPullStart: 'docker_pull_start',
  dockerServiceLogsStart: 'docker_service_logs_start',
  dockerServiceLogsStop: 'docker_service_logs_stop',
} as const;
